//! `vpsagent-runtime`: агентный harness — цикл, инструменты, права, память.

pub mod ab;
pub mod agent_loop;
pub mod classifier;
pub mod commands;
pub mod compact;
pub mod context;
pub mod critic;
pub mod definition;
pub mod hooks;
pub mod mcp;
pub mod mcp_server;
pub mod memory;
pub mod pending;
pub mod permissions;
pub mod rewind;
pub mod skills;
pub mod skills_validate;
pub mod subagent;
pub mod tools;
pub mod truncate;

pub use ab::{AbResult, AbRun, AbRunner};
pub use agent_loop::{run_agent, AgentParams};
pub use classifier::{classify, is_multiplex_command, Route};
pub use compact::{compact, estimate_tokens, COMPACT_THRESHOLD};
pub use hooks::{HookConfig, HookEvent, Hooks};
pub use mcp::{full_tool_name, McpClient, McpServerConfig, McpTool};
pub use mcp_server::serve_mcp;
pub use rewind::{RewindStore, SessionSnapshot};
pub use commands::{Command, CommandRegistry};
pub use critic::{code_reviewer_definition, run_review, ReviewResult, CODE_REVIEWER_PROMPT, MAX_REVIEW_ITERATIONS};
pub use definition::{AgentDefinition, DefinitionRegistry};
pub use pending::{Answer, PendingPermissions, PendingRequests};
pub use permissions::{Decision, Permissions};
pub use skills::{Skill, SkillRegistry};
pub use skills_validate::{template, validate_generated, Validation};
pub use subagent::SubagentManager;
pub use tools::{Registry, Tool, ToolContext, ToolOutput};